[build]
  command = "rm -rf node_modules .next && npm install && npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_FLAGS = "--legacy-peer-deps"